// Skill Data - Comprehensive skill trees for each class
// Each class has 8 skills: 4 active + 4 passive

import { ClassSkillTree, Skill } from '@/types/skills';
import { CharacterClass } from '@/types/classes';

// ============ WARRIOR SKILLS ============
const warriorSkills: Skill[] = [
  // Active Skills
  {
    id: 'warrior_shield_bash',
    name: 'Shield Bash',
    description: 'Smash enemy with your shield, dealing damage and stunning for 1 turn.',
    type: 'active',
    icon: 'Shield',
    visualEffect: 'physical',
    manaCost: 15,
    cooldown: 3,
    targetType: 'enemy',
    maxRank: 3,
    rankBonuses: [1, 1.5, 2],
    effects: [
      { type: 'damage', value: 15, scaling: { stat: 'strength', ratio: 0.5 } },
      { type: 'stun', value: 1 },
    ],
  },
  {
    id: 'warrior_battle_cry',
    name: 'Battle Cry',
    description: 'Let out a fierce war cry, boosting attack for 3 turns.',
    type: 'active',
    icon: 'Volume2',
    visualEffect: 'buff',
    manaCost: 20,
    cooldown: 5,
    targetType: 'self',
    maxRank: 3,
    rankBonuses: [1, 1.3, 1.6],
    requiredLevel: 2,
    effects: [
      { type: 'buff_attack', value: 25, duration: 3 },
    ],
  },
  {
    id: 'warrior_execute',
    name: 'Execute',
    description: 'Powerful strike that deals bonus damage to low health enemies.',
    type: 'active',
    icon: 'Sword',
    visualEffect: 'physical',
    manaCost: 25,
    cooldown: 4,
    targetType: 'enemy',
    maxRank: 3,
    rankBonuses: [1, 1.4, 1.8],
    requiredLevel: 4,
    requiredSkillId: 'warrior_shield_bash',
    effects: [
      { type: 'damage', value: 35, scaling: { stat: 'strength', ratio: 1.0 } },
    ],
  },
  {
    id: 'warrior_iron_fortress',
    name: 'Iron Fortress',
    description: 'Become an immovable fortress, gaining a powerful shield and defense buff.',
    type: 'active',
    icon: 'ShieldCheck',
    visualEffect: 'shield',
    manaCost: 30,
    cooldown: 6,
    targetType: 'self',
    maxRank: 3,
    rankBonuses: [1, 1.4, 1.8],
    requiredLevel: 6,
    requiredSkillId: 'warrior_battle_cry',
    effects: [
      { type: 'shield', value: 40, scaling: { stat: 'strength', ratio: 0.6 } },
      { type: 'buff_defense', value: 30, duration: 3 },
    ],
  },
  // Passive Skills
  {
    id: 'warrior_toughness',
    name: 'Toughness',
    description: 'Increases maximum health.',
    type: 'passive',
    icon: 'Heart',
    manaCost: 0,
    targetType: 'none',
    maxRank: 3,
    effects: [],
    passiveBonus: [{ stat: 'maxHealth', value: 15 }],
  },
  {
    id: 'warrior_armor_mastery',
    name: 'Armor Mastery',
    description: 'Increases defense from all sources.',
    type: 'passive',
    icon: 'ShieldCheck',
    manaCost: 0,
    targetType: 'none',
    maxRank: 3,
    requiredLevel: 2,
    effects: [],
    passiveBonus: [{ stat: 'defense', value: 3 }],
  },
  {
    id: 'warrior_bloodthirst',
    name: 'Bloodthirst',
    description: 'Gain life steal on all attacks.',
    type: 'passive',
    icon: 'Droplet',
    manaCost: 0,
    targetType: 'none',
    maxRank: 3,
    requiredLevel: 4,
    requiredSkillId: 'warrior_toughness',
    effects: [],
    passiveBonus: [{ stat: 'lifeSteal', value: 3 }],
  },
  {
    id: 'warrior_veterans_might',
    name: "Veteran's Might",
    description: 'Increases attack power and critical damage.',
    type: 'passive',
    icon: 'Sword',
    manaCost: 0,
    targetType: 'none',
    maxRank: 3,
    requiredLevel: 5,
    requiredSkillId: 'warrior_armor_mastery',
    effects: [],
    passiveBonus: [
      { stat: 'attack', value: 4 },
      { stat: 'critDamage', value: 8 },
    ],
  },
];

// ============ ROGUE SKILLS ============
const rogueSkills: Skill[] = [
  {
    id: 'rogue_backstab',
    name: 'Backstab',
    description: 'Strike from the shadows with guaranteed critical hit.',
    type: 'active',
    icon: 'Target',
    visualEffect: 'shadow',
    manaCost: 20,
    cooldown: 3,
    targetType: 'enemy',
    maxRank: 3,
    rankBonuses: [1, 1.4, 1.8],
    effects: [
      { type: 'damage', value: 25, scaling: { stat: 'dexterity', ratio: 0.8 } },
    ],
  },
  {
    id: 'rogue_smoke_bomb',
    name: 'Smoke Bomb',
    description: 'Create a smoke screen, greatly increasing dodge for 2 turns.',
    type: 'active',
    icon: 'Cloud',
    visualEffect: 'shadow',
    manaCost: 18,
    cooldown: 4,
    targetType: 'self',
    maxRank: 3,
    rankBonuses: [1, 1.3, 1.6],
    requiredLevel: 2,
    effects: [
      { type: 'buff_defense', value: 50, duration: 2 },
    ],
  },
  {
    id: 'rogue_poison_blade',
    name: 'Poison Blade',
    description: 'Coat weapon in poison, causing bleed damage over 3 turns.',
    type: 'active',
    icon: 'Skull',
    visualEffect: 'nature',
    manaCost: 22,
    cooldown: 5,
    targetType: 'enemy',
    maxRank: 3,
    rankBonuses: [1, 1.5, 2],
    requiredLevel: 4,
    requiredSkillId: 'rogue_backstab',
    effects: [
      { type: 'damage', value: 10, scaling: { stat: 'dexterity', ratio: 0.3 } },
      { type: 'bleed', value: 8, duration: 3 },
    ],
  },
  {
    id: 'rogue_shadow_dance',
    name: 'Shadow Dance',
    description: 'Dance through shadows, striking multiple times with increased crit.',
    type: 'active',
    icon: 'Sparkles',
    visualEffect: 'shadow',
    manaCost: 35,
    cooldown: 6,
    targetType: 'enemy',
    maxRank: 3,
    rankBonuses: [1, 1.5, 2],
    requiredLevel: 6,
    requiredSkillId: 'rogue_smoke_bomb',
    effects: [
      { type: 'damage', value: 20, scaling: { stat: 'dexterity', ratio: 0.6 } },
      { type: 'damage', value: 20, scaling: { stat: 'dexterity', ratio: 0.6 } },
      { type: 'buff_crit', value: 30, duration: 2 },
    ],
  },
  {
    id: 'rogue_agility',
    name: 'Agility',
    description: 'Increases dodge chance.',
    type: 'passive',
    icon: 'Zap',
    manaCost: 0,
    targetType: 'none',
    maxRank: 3,
    effects: [],
    passiveBonus: [{ stat: 'dodge', value: 3 }],
  },
  {
    id: 'rogue_precision',
    name: 'Precision',
    description: 'Increases critical hit chance.',
    type: 'passive',
    icon: 'Crosshair',
    manaCost: 0,
    targetType: 'none',
    maxRank: 3,
    requiredLevel: 2,
    effects: [],
    passiveBonus: [{ stat: 'critChance', value: 4 }],
  },
  {
    id: 'rogue_lethality',
    name: 'Lethality',
    description: 'Increases critical hit damage.',
    type: 'passive',
    icon: 'Flame',
    manaCost: 0,
    targetType: 'none',
    maxRank: 3,
    requiredLevel: 4,
    requiredSkillId: 'rogue_precision',
    effects: [],
    passiveBonus: [{ stat: 'critDamage', value: 15 }],
  },
  {
    id: 'rogue_assassin',
    name: 'Assassin',
    description: 'Increases attack and gold find.',
    type: 'passive',
    icon: 'Target',
    manaCost: 0,
    targetType: 'none',
    maxRank: 3,
    requiredLevel: 5,
    requiredSkillId: 'rogue_agility',
    effects: [],
    passiveBonus: [
      { stat: 'attack', value: 3 },
      { stat: 'goldFind', value: 5 },
    ],
  },
];

// ============ MAGE SKILLS ============
const mageSkills: Skill[] = [
  {
    id: 'mage_fireball',
    name: 'Fireball',
    description: 'Hurl a ball of fire dealing heavy magic damage.',
    type: 'active',
    icon: 'Flame',
    visualEffect: 'fire',
    manaCost: 18,
    cooldown: 2,
    targetType: 'enemy',
    maxRank: 3,
    rankBonuses: [1, 1.5, 2],
    effects: [
      { type: 'magic_damage', value: 30, scaling: { stat: 'intelligence', ratio: 1.2 } },
    ],
  },
  {
    id: 'mage_ice_barrier',
    name: 'Ice Barrier',
    description: 'Create a magical shield that absorbs damage.',
    type: 'active',
    icon: 'Snowflake',
    visualEffect: 'ice',
    manaCost: 25,
    cooldown: 5,
    targetType: 'self',
    maxRank: 3,
    rankBonuses: [1, 1.4, 1.8],
    requiredLevel: 2,
    effects: [
      { type: 'shield', value: 30, scaling: { stat: 'intelligence', ratio: 0.8 } },
    ],
  },
  {
    id: 'mage_arcane_blast',
    name: 'Arcane Blast',
    description: 'Unleash raw arcane energy, ignoring enemy magic defense.',
    type: 'active',
    icon: 'Sparkles',
    visualEffect: 'holy',
    manaCost: 35,
    cooldown: 4,
    targetType: 'enemy',
    maxRank: 3,
    rankBonuses: [1, 1.5, 2],
    requiredLevel: 4,
    requiredSkillId: 'mage_fireball',
    effects: [
      { type: 'magic_damage', value: 45, scaling: { stat: 'intelligence', ratio: 1.5 } },
    ],
  },
  {
    id: 'mage_meteor',
    name: 'Meteor',
    description: 'Call down a devastating meteor dealing massive fire damage.',
    type: 'active',
    icon: 'Flame',
    visualEffect: 'fire',
    manaCost: 50,
    cooldown: 7,
    targetType: 'enemy',
    maxRank: 3,
    rankBonuses: [1, 1.4, 1.8],
    requiredLevel: 6,
    requiredSkillId: 'mage_arcane_blast',
    effects: [
      { type: 'magic_damage', value: 70, scaling: { stat: 'intelligence', ratio: 2.0 } },
      { type: 'bleed', value: 10, duration: 2 },
    ],
  },
  {
    id: 'mage_arcane_intellect',
    name: 'Arcane Intellect',
    description: 'Increases maximum mana.',
    type: 'passive',
    icon: 'Brain',
    manaCost: 0,
    targetType: 'none',
    maxRank: 3,
    effects: [],
    passiveBonus: [{ stat: 'maxMana', value: 15 }],
  },
  {
    id: 'mage_spell_power',
    name: 'Spell Power',
    description: 'Increases magic attack.',
    type: 'passive',
    icon: 'Wand2',
    manaCost: 0,
    targetType: 'none',
    maxRank: 3,
    requiredLevel: 2,
    effects: [],
    passiveBonus: [{ stat: 'magicAttack', value: 5 }],
  },
  {
    id: 'mage_mana_shield',
    name: 'Mana Shield',
    description: 'Increases magic defense.',
    type: 'passive',
    icon: 'Shield',
    manaCost: 0,
    targetType: 'none',
    maxRank: 3,
    requiredLevel: 4,
    requiredSkillId: 'mage_arcane_intellect',
    effects: [],
    passiveBonus: [{ stat: 'magicDefense', value: 4 }],
  },
  {
    id: 'mage_archmage',
    name: 'Archmage',
    description: 'Increases magic attack and critical chance.',
    type: 'passive',
    icon: 'Star',
    manaCost: 0,
    targetType: 'none',
    maxRank: 3,
    requiredLevel: 5,
    requiredSkillId: 'mage_spell_power',
    effects: [],
    passiveBonus: [
      { stat: 'magicAttack', value: 4 },
      { stat: 'critChance', value: 3 },
    ],
  },
];

// ============ CLERIC SKILLS ============
const clericSkills: Skill[] = [
  {
    id: 'cleric_heal',
    name: 'Holy Light',
    description: 'Channel divine energy to restore health.',
    type: 'active',
    icon: 'Heart',
    visualEffect: 'heal',
    manaCost: 20,
    cooldown: 2,
    targetType: 'self',
    maxRank: 3,
    rankBonuses: [1, 1.4, 1.8],
    effects: [
      { type: 'heal', value: 35, scaling: { stat: 'intelligence', ratio: 0.8 } },
    ],
  },
  {
    id: 'cleric_smite',
    name: 'Smite',
    description: 'Call down holy wrath upon your enemy.',
    type: 'active',
    icon: 'Zap',
    visualEffect: 'holy',
    manaCost: 18,
    cooldown: 3,
    targetType: 'enemy',
    maxRank: 3,
    rankBonuses: [1, 1.4, 1.8],
    requiredLevel: 2,
    effects: [
      { type: 'magic_damage', value: 25, scaling: { stat: 'intelligence', ratio: 0.9 } },
    ],
  },
  {
    id: 'cleric_divine_shield',
    name: 'Divine Shield',
    description: 'Surround yourself with holy protection, boosting defense and healing.',
    type: 'active',
    icon: 'ShieldCheck',
    visualEffect: 'shield',
    manaCost: 25,
    cooldown: 5,
    targetType: 'self',
    maxRank: 3,
    rankBonuses: [1, 1.3, 1.6],
    requiredLevel: 4,
    requiredSkillId: 'cleric_heal',
    effects: [
      { type: 'buff_defense', value: 40, duration: 3 },
      { type: 'heal', value: 15 },
    ],
  },
  {
    id: 'cleric_divine_wrath',
    name: 'Divine Wrath',
    description: 'Unleash the full fury of the divine, dealing holy damage and stunning.',
    type: 'active',
    icon: 'Sparkles',
    visualEffect: 'holy',
    manaCost: 40,
    cooldown: 6,
    targetType: 'enemy',
    maxRank: 3,
    rankBonuses: [1, 1.5, 2],
    requiredLevel: 6,
    requiredSkillId: 'cleric_smite',
    effects: [
      { type: 'magic_damage', value: 50, scaling: { stat: 'intelligence', ratio: 1.3 } },
      { type: 'stun', value: 1 },
      { type: 'heal', value: 20 },
    ],
  },
  {
    id: 'cleric_inner_peace',
    name: 'Inner Peace',
    description: 'Increases maximum health and mana.',
    type: 'passive',
    icon: 'Sparkles',
    manaCost: 0,
    targetType: 'none',
    maxRank: 3,
    effects: [],
    passiveBonus: [
      { stat: 'maxHealth', value: 10 },
      { stat: 'maxMana', value: 10 },
    ],
  },
  {
    id: 'cleric_holy_fortitude',
    name: 'Holy Fortitude',
    description: 'Increases defense and magic defense.',
    type: 'passive',
    icon: 'Shield',
    manaCost: 0,
    targetType: 'none',
    maxRank: 3,
    requiredLevel: 2,
    effects: [],
    passiveBonus: [
      { stat: 'defense', value: 2 },
      { stat: 'magicDefense', value: 2 },
    ],
  },
  {
    id: 'cleric_blessed',
    name: 'Blessed',
    description: 'Increases experience gained from combat.',
    type: 'passive',
    icon: 'Star',
    manaCost: 0,
    targetType: 'none',
    maxRank: 3,
    requiredLevel: 4,
    requiredSkillId: 'cleric_inner_peace',
    effects: [],
    passiveBonus: [{ stat: 'expBonus', value: 5 }],
  },
  {
    id: 'cleric_divine_grace',
    name: 'Divine Grace',
    description: 'Increases magic attack and life steal.',
    type: 'passive',
    icon: 'Heart',
    manaCost: 0,
    targetType: 'none',
    maxRank: 3,
    requiredLevel: 5,
    requiredSkillId: 'cleric_holy_fortitude',
    effects: [],
    passiveBonus: [
      { stat: 'magicAttack', value: 3 },
      { stat: 'lifeSteal', value: 2 },
    ],
  },
];

// ============ BARBARIAN SKILLS ============
const barbarianSkills: Skill[] = [
  {
    id: 'barbarian_rage',
    name: 'Rage',
    description: 'Enter a berserker rage, massively boosting attack for 3 turns.',
    type: 'active',
    icon: 'Flame',
    visualEffect: 'fire',
    manaCost: 10,
    cooldown: 4,
    targetType: 'self',
    maxRank: 3,
    rankBonuses: [1, 1.3, 1.6],
    effects: [
      { type: 'buff_attack', value: 50, duration: 3 },
    ],
  },
  {
    id: 'barbarian_whirlwind',
    name: 'Whirlwind',
    description: 'Spin with devastating force, dealing damage that ignores armor.',
    type: 'active',
    icon: 'RotateCcw',
    visualEffect: 'physical',
    manaCost: 25,
    cooldown: 4,
    targetType: 'enemy',
    maxRank: 3,
    rankBonuses: [1, 1.5, 2],
    requiredLevel: 2,
    effects: [
      { type: 'damage', value: 35, scaling: { stat: 'strength', ratio: 1.2 } },
    ],
  },
  {
    id: 'barbarian_bloodlust',
    name: 'Bloodlust',
    description: 'Savage attack that heals you based on damage dealt.',
    type: 'active',
    icon: 'Droplet',
    visualEffect: 'shadow',
    manaCost: 20,
    cooldown: 5,
    targetType: 'enemy',
    maxRank: 3,
    rankBonuses: [1, 1.4, 1.8],
    requiredLevel: 4,
    requiredSkillId: 'barbarian_rage',
    effects: [
      { type: 'lifesteal_attack', value: 30, scaling: { stat: 'strength', ratio: 0.8 } },
    ],
  },
  {
    id: 'barbarian_rampage',
    name: 'Rampage',
    description: 'Go on a rampage dealing multiple hits and gaining attack boost.',
    type: 'active',
    icon: 'Axe',
    visualEffect: 'physical',
    manaCost: 35,
    cooldown: 6,
    targetType: 'enemy',
    maxRank: 3,
    rankBonuses: [1, 1.5, 2],
    requiredLevel: 6,
    requiredSkillId: 'barbarian_whirlwind',
    effects: [
      { type: 'damage', value: 25, scaling: { stat: 'strength', ratio: 0.7 } },
      { type: 'damage', value: 25, scaling: { stat: 'strength', ratio: 0.7 } },
      { type: 'damage', value: 25, scaling: { stat: 'strength', ratio: 0.7 } },
      { type: 'buff_attack', value: 20, duration: 2 },
    ],
  },
  {
    id: 'barbarian_thick_skin',
    name: 'Thick Skin',
    description: 'Greatly increases maximum health.',
    type: 'passive',
    icon: 'Heart',
    manaCost: 0,
    targetType: 'none',
    maxRank: 3,
    effects: [],
    passiveBonus: [{ stat: 'maxHealth', value: 20 }],
  },
  {
    id: 'barbarian_brute_force',
    name: 'Brute Force',
    description: 'Increases attack power.',
    type: 'passive',
    icon: 'Sword',
    manaCost: 0,
    targetType: 'none',
    maxRank: 3,
    requiredLevel: 2,
    effects: [],
    passiveBonus: [{ stat: 'attack', value: 4 }],
  },
  {
    id: 'barbarian_savage',
    name: 'Savage',
    description: 'Increases critical hit chance and damage.',
    type: 'passive',
    icon: 'Axe',
    manaCost: 0,
    targetType: 'none',
    maxRank: 3,
    requiredLevel: 4,
    requiredSkillId: 'barbarian_brute_force',
    effects: [],
    passiveBonus: [
      { stat: 'critChance', value: 3 },
      { stat: 'critDamage', value: 10 },
    ],
  },
  {
    id: 'barbarian_warlord',
    name: 'Warlord',
    description: 'Increases attack, defense, and life steal.',
    type: 'passive',
    icon: 'Shield',
    manaCost: 0,
    targetType: 'none',
    maxRank: 3,
    requiredLevel: 5,
    requiredSkillId: 'barbarian_thick_skin',
    effects: [],
    passiveBonus: [
      { stat: 'attack', value: 3 },
      { stat: 'defense', value: 2 },
      { stat: 'lifeSteal', value: 2 },
    ],
  },
];

// ============ ARCHER SKILLS ============
const archerSkills: Skill[] = [
  {
    id: 'archer_aimed_shot',
    name: 'Aimed Shot',
    description: 'Carefully aimed shot with increased critical chance.',
    type: 'active',
    icon: 'Crosshair',
    visualEffect: 'physical',
    manaCost: 15,
    cooldown: 2,
    targetType: 'enemy',
    maxRank: 3,
    rankBonuses: [1, 1.4, 1.8],
    effects: [
      { type: 'damage', value: 20, scaling: { stat: 'dexterity', ratio: 0.9 } },
      { type: 'buff_crit', value: 20, duration: 1 },
    ],
  },
  {
    id: 'archer_rain_of_arrows',
    name: 'Rain of Arrows',
    description: 'Unleash a barrage of arrows striking multiple times.',
    type: 'active',
    icon: 'CloudRain',
    visualEffect: 'physical',
    manaCost: 30,
    cooldown: 5,
    targetType: 'enemy',
    maxRank: 3,
    rankBonuses: [1, 1.5, 2],
    requiredLevel: 2,
    effects: [
      { type: 'damage', value: 12, scaling: { stat: 'dexterity', ratio: 0.4 } },
      { type: 'damage', value: 12, scaling: { stat: 'dexterity', ratio: 0.4 } },
      { type: 'damage', value: 12, scaling: { stat: 'dexterity', ratio: 0.4 } },
    ],
  },
  {
    id: 'archer_piercing_shot',
    name: 'Piercing Shot',
    description: 'Armor-piercing arrow that ignores enemy defense.',
    type: 'active',
    icon: 'ArrowRight',
    visualEffect: 'physical',
    manaCost: 25,
    cooldown: 4,
    targetType: 'enemy',
    maxRank: 3,
    rankBonuses: [1, 1.5, 2],
    requiredLevel: 4,
    requiredSkillId: 'archer_aimed_shot',
    effects: [
      { type: 'damage', value: 40, scaling: { stat: 'dexterity', ratio: 1.2 } },
    ],
  },
  {
    id: 'archer_explosive_arrow',
    name: 'Explosive Arrow',
    description: 'Fire an explosive arrow dealing fire damage and causing burn.',
    type: 'active',
    icon: 'Flame',
    visualEffect: 'fire',
    manaCost: 35,
    cooldown: 6,
    targetType: 'enemy',
    maxRank: 3,
    rankBonuses: [1, 1.5, 2],
    requiredLevel: 6,
    requiredSkillId: 'archer_rain_of_arrows',
    effects: [
      { type: 'damage', value: 45, scaling: { stat: 'dexterity', ratio: 1.0 } },
      { type: 'bleed', value: 12, duration: 3 },
    ],
  },
  {
    id: 'archer_eagle_eye',
    name: 'Eagle Eye',
    description: 'Increases critical hit chance.',
    type: 'passive',
    icon: 'Eye',
    manaCost: 0,
    targetType: 'none',
    maxRank: 3,
    effects: [],
    passiveBonus: [{ stat: 'critChance', value: 5 }],
  },
  {
    id: 'archer_swift_quiver',
    name: 'Swift Quiver',
    description: 'Increases attack power.',
    type: 'passive',
    icon: 'Zap',
    manaCost: 0,
    targetType: 'none',
    maxRank: 3,
    requiredLevel: 2,
    effects: [],
    passiveBonus: [{ stat: 'attack', value: 3 }],
  },
  {
    id: 'archer_evasive',
    name: 'Evasive',
    description: 'Increases dodge chance.',
    type: 'passive',
    icon: 'Wind',
    manaCost: 0,
    targetType: 'none',
    maxRank: 3,
    requiredLevel: 4,
    requiredSkillId: 'archer_eagle_eye',
    effects: [],
    passiveBonus: [{ stat: 'dodge', value: 4 }],
  },
  {
    id: 'archer_sharpshooter',
    name: 'Sharpshooter',
    description: 'Increases attack, crit chance, and crit damage.',
    type: 'passive',
    icon: 'Target',
    manaCost: 0,
    targetType: 'none',
    maxRank: 3,
    requiredLevel: 5,
    requiredSkillId: 'archer_swift_quiver',
    effects: [],
    passiveBonus: [
      { stat: 'attack', value: 2 },
      { stat: 'critChance', value: 3 },
      { stat: 'critDamage', value: 10 },
    ],
  },
];

// Class skill tree map
export const CLASS_SKILL_TREES: Record<CharacterClass, ClassSkillTree> = {
  warrior: { className: 'warrior', skills: warriorSkills },
  rogue: { className: 'rogue', skills: rogueSkills },
  mage: { className: 'mage', skills: mageSkills },
  cleric: { className: 'cleric', skills: clericSkills },
  barbarian: { className: 'barbarian', skills: barbarianSkills },
  archer: { className: 'archer', skills: archerSkills },
};

// Get all skills for a class
export function getClassSkills(characterClass: CharacterClass): Skill[] {
  return CLASS_SKILL_TREES[characterClass].skills;
}

// Get a specific skill by ID
export function getSkillById(skillId: string, characterClass: CharacterClass): Skill | undefined {
  return CLASS_SKILL_TREES[characterClass].skills.find(s => s.id === skillId);
}

// Check if a skill can be learned
export function canLearnSkill(
  skill: Skill,
  characterLevel: number,
  learnedSkills: { skillId: string; rank: number }[]
): { canLearn: boolean; reason?: string } {
  // Check level requirement
  if (skill.requiredLevel && characterLevel < skill.requiredLevel) {
    return { canLearn: false, reason: `Requires level ${skill.requiredLevel}` };
  }
  
  // Check prerequisite skill
  if (skill.requiredSkillId) {
    const hasPrereq = learnedSkills.some(
      ls => ls.skillId === skill.requiredSkillId && ls.rank >= 1
    );
    if (!hasPrereq) {
      const prereqSkill = warriorSkills.concat(rogueSkills, mageSkills, clericSkills, barbarianSkills, archerSkills)
        .find(s => s.id === skill.requiredSkillId);
      return { canLearn: false, reason: `Requires ${prereqSkill?.name || 'prerequisite skill'}` };
    }
  }
  
  // Check if already at max rank
  const learned = learnedSkills.find(ls => ls.skillId === skill.id);
  if (learned && learned.rank >= skill.maxRank) {
    return { canLearn: false, reason: 'Already at max rank' };
  }
  
  return { canLearn: true };
}
